### ISSUE TITLE
flyctl is out of date?

### ISSUE THREAD

**Issue by karlhorky** [piraces/chocolatey-packages#2]
Hi @piraces, thanks for these packages! 🙌

A student was just using the version of [your `flyctl` package](https://community.chocolatey.org/packages/flyctl) (`v0.0.393` at the time of writing) and it appears to be out of date?

```bash
$ flyctl auth login
Update available 0.0.393 -> v0.0.411.
Run "flyctl.exe version update" to upgrade.
```

I assume that using the `version update` command would work, but it would be nice for the version installed over Chocolatey to be the latest version.

**Comment by piraces** [comment]
Hi @karlhorky , thanks!

Thanks for noticing this! It turns out the automatic process of updating packages is failing... I will fix it and update the status here 👍

**Comment by piraces** [comment]
Hi again @karlhorky . The fix is now working and `flyctl` is now in the latest version ([v0.0.411](https://github.com/superfly/flyctl/releases/tag/v0.0.411)).
Nevertheless, [it is awating moderation from the chocolatey mods](https://community.chocolatey.org/packages/flyctl/0.0.411), we will have to wait some time until it is listed and can be upgraded through a normal `choco upgrade`.

You can force the install of the newest version with the following command:
```pwsh
choco install flyctl --version=0.0.411 --force
```

**Comment by karlhorky** [comment]
Great, thanks for the quick resolution @piraces 🙌
